import type { Metadata } from 'next'
import { Roboto } from 'next/font/google'
import './globals.css'
import styles from './ui/layout.module.css'

const roboto = Roboto({ weight: ['400', '500', '700'], subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Service Desk',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <div className={styles.container}>
          <div className={styles.menu}></div>
          <div className={styles.content}>{children}</div>
        </div>
      </body>
    </html>
  )
}
